<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnitSystem\UnitSystem.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="FlowsheetSolvers\" />
    <Folder Include="Final Solver\" />
    <Folder Include="MatrixSolvers\" />
    <Folder Include="SolverQwen\Equipments\" />
    <Folder Include="UnitOperations\HeatExchangers\" />
    <Folder Include="UnitOperations\Pumps\" />
  </ItemGroup>

</Project>
