using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Server.Migrations
{
    /// <inheritdoc />
    public partial class ComponentEntityAndIdentityRefactor : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ChemicalComponents",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: false),
                    Formula = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    StructuralFormula = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: false),
                    Family = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    SecondaryFamily = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    MolecularWeight = table.Column<double>(type: "float", nullable: false),
                    CriticalTemperature_Value = table.Column<double>(type: "float", nullable: false),
                    CriticalTemperature_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    BoilingPoint_Value = table.Column<double>(type: "float", nullable: false),
                    BoilingPoint_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    MeltingPoint_Value = table.Column<double>(type: "float", nullable: false),
                    MeltingPoint_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    CriticalPressure_Value = table.Column<double>(type: "float", nullable: false),
                    CriticalPressure_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    CriticalVolume_Value = table.Column<double>(type: "float", nullable: false),
                    CriticalVolume_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    VolumeAsterisk_Value = table.Column<double>(type: "float", nullable: false),
                    VolumeAsterisk_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    EnthalpyForm_Value = table.Column<double>(type: "float", nullable: false),
                    EnthalpyForm_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    GibbsForm_Value = table.Column<double>(type: "float", nullable: false),
                    GibbsForm_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    EntropyForm_Value = table.Column<double>(type: "float", nullable: false),
                    EntropyForm_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    CombustionEnthalpy_Value = table.Column<double>(type: "float", nullable: false),
                    CombustionEnthalpy_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    CriticalZ = table.Column<double>(type: "float", nullable: false),
                    AcentricFactor = table.Column<double>(type: "float", nullable: false),
                    AcentricFactorPitzer = table.Column<double>(type: "float", nullable: false),
                    VaporPressure_C1 = table.Column<double>(type: "float", nullable: false),
                    VaporPressure_C2 = table.Column<double>(type: "float", nullable: false),
                    VaporPressure_C3 = table.Column<double>(type: "float", nullable: false),
                    VaporPressure_C4 = table.Column<double>(type: "float", nullable: false),
                    VaporPressure_C5 = table.Column<double>(type: "float", nullable: false),
                    VaporPressure_C6 = table.Column<double>(type: "float", nullable: false),
                    VaporPressure_C7 = table.Column<double>(type: "float", nullable: false),
                    VaporPressure_Tmin_Value = table.Column<double>(type: "float", nullable: false),
                    VaporPressure_Tmin_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    VaporPressure_Tmax_Value = table.Column<double>(type: "float", nullable: false),
                    VaporPressure_Tmax_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    HeatOfVaporization_C1 = table.Column<double>(type: "float", nullable: false),
                    HeatOfVaporization_C2 = table.Column<double>(type: "float", nullable: false),
                    HeatOfVaporization_C3 = table.Column<double>(type: "float", nullable: false),
                    HeatOfVaporization_C4 = table.Column<double>(type: "float", nullable: false),
                    HeatOfVaporization_C5 = table.Column<double>(type: "float", nullable: false),
                    HeatOfVaporization_C6 = table.Column<double>(type: "float", nullable: false),
                    HeatOfVaporization_C7 = table.Column<double>(type: "float", nullable: false),
                    HeatOfVaporization_Tmin_Value = table.Column<double>(type: "float", nullable: false),
                    HeatOfVaporization_Tmin_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    HeatOfVaporization_Tmax_Value = table.Column<double>(type: "float", nullable: false),
                    HeatOfVaporization_Tmax_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    LiquidHeatCapacity_C1 = table.Column<double>(type: "float", nullable: false),
                    LiquidHeatCapacity_C2 = table.Column<double>(type: "float", nullable: false),
                    LiquidHeatCapacity_C3 = table.Column<double>(type: "float", nullable: false),
                    LiquidHeatCapacity_C4 = table.Column<double>(type: "float", nullable: false),
                    LiquidHeatCapacity_C5 = table.Column<double>(type: "float", nullable: false),
                    LiquidHeatCapacity_C6 = table.Column<double>(type: "float", nullable: false),
                    LiquidHeatCapacity_C7 = table.Column<double>(type: "float", nullable: false),
                    LiquidHeatCapacity_Tmin_Value = table.Column<double>(type: "float", nullable: false),
                    LiquidHeatCapacity_Tmin_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    LiquidHeatCapacity_Tmax_Value = table.Column<double>(type: "float", nullable: false),
                    LiquidHeatCapacity_Tmax_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    GasHeatCapacity_C1 = table.Column<double>(type: "float", nullable: false),
                    GasHeatCapacity_C2 = table.Column<double>(type: "float", nullable: false),
                    GasHeatCapacity_C3 = table.Column<double>(type: "float", nullable: false),
                    GasHeatCapacity_C4 = table.Column<double>(type: "float", nullable: false),
                    GasHeatCapacity_C5 = table.Column<double>(type: "float", nullable: false),
                    GasHeatCapacity_C6 = table.Column<double>(type: "float", nullable: false),
                    GasHeatCapacity_C7 = table.Column<double>(type: "float", nullable: false),
                    GasHeatCapacity_Tmin_Value = table.Column<double>(type: "float", nullable: false),
                    GasHeatCapacity_Tmin_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    GasHeatCapacity_Tmax_Value = table.Column<double>(type: "float", nullable: false),
                    GasHeatCapacity_Tmax_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    LiquidViscosity_C1 = table.Column<double>(type: "float", nullable: false),
                    LiquidViscosity_C2 = table.Column<double>(type: "float", nullable: false),
                    LiquidViscosity_C3 = table.Column<double>(type: "float", nullable: false),
                    LiquidViscosity_C4 = table.Column<double>(type: "float", nullable: false),
                    LiquidViscosity_C5 = table.Column<double>(type: "float", nullable: false),
                    LiquidViscosity_C6 = table.Column<double>(type: "float", nullable: false),
                    LiquidViscosity_C7 = table.Column<double>(type: "float", nullable: false),
                    LiquidViscosity_Tmin_Value = table.Column<double>(type: "float", nullable: false),
                    LiquidViscosity_Tmin_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    LiquidViscosity_Tmax_Value = table.Column<double>(type: "float", nullable: false),
                    LiquidViscosity_Tmax_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    GasViscosity_C1 = table.Column<double>(type: "float", nullable: false),
                    GasViscosity_C2 = table.Column<double>(type: "float", nullable: false),
                    GasViscosity_C3 = table.Column<double>(type: "float", nullable: false),
                    GasViscosity_C4 = table.Column<double>(type: "float", nullable: false),
                    GasViscosity_C5 = table.Column<double>(type: "float", nullable: false),
                    GasViscosity_C6 = table.Column<double>(type: "float", nullable: false),
                    GasViscosity_C7 = table.Column<double>(type: "float", nullable: false),
                    GasViscosity_Tmin_Value = table.Column<double>(type: "float", nullable: false),
                    GasViscosity_Tmin_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    GasViscosity_Tmax_Value = table.Column<double>(type: "float", nullable: false),
                    GasViscosity_Tmax_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    LiquidThermalCond_C1 = table.Column<double>(type: "float", nullable: false),
                    LiquidThermalCond_C2 = table.Column<double>(type: "float", nullable: false),
                    LiquidThermalCond_C3 = table.Column<double>(type: "float", nullable: false),
                    LiquidThermalCond_C4 = table.Column<double>(type: "float", nullable: false),
                    LiquidThermalCond_C5 = table.Column<double>(type: "float", nullable: false),
                    LiquidThermalCond_C6 = table.Column<double>(type: "float", nullable: false),
                    LiquidThermalCond_C7 = table.Column<double>(type: "float", nullable: false),
                    LiquidThermalCond_Tmin_Value = table.Column<double>(type: "float", nullable: false),
                    LiquidThermalCond_Tmin_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    LiquidThermalCond_Tmax_Value = table.Column<double>(type: "float", nullable: false),
                    LiquidThermalCond_Tmax_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    GasThermalCond_C1 = table.Column<double>(type: "float", nullable: false),
                    GasThermalCond_C2 = table.Column<double>(type: "float", nullable: false),
                    GasThermalCond_C3 = table.Column<double>(type: "float", nullable: false),
                    GasThermalCond_C4 = table.Column<double>(type: "float", nullable: false),
                    GasThermalCond_C5 = table.Column<double>(type: "float", nullable: false),
                    GasThermalCond_C6 = table.Column<double>(type: "float", nullable: false),
                    GasThermalCond_C7 = table.Column<double>(type: "float", nullable: false),
                    GasThermalCond_Tmin_Value = table.Column<double>(type: "float", nullable: false),
                    GasThermalCond_Tmin_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    GasThermalCond_Tmax_Value = table.Column<double>(type: "float", nullable: false),
                    GasThermalCond_Tmax_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Density_C1 = table.Column<double>(type: "float", nullable: false),
                    Density_C2 = table.Column<double>(type: "float", nullable: false),
                    Density_C3 = table.Column<double>(type: "float", nullable: false),
                    Density_C4 = table.Column<double>(type: "float", nullable: false),
                    Density_C5 = table.Column<double>(type: "float", nullable: false),
                    Density_C6 = table.Column<double>(type: "float", nullable: false),
                    Density_C7 = table.Column<double>(type: "float", nullable: false),
                    Density_Tmin_Value = table.Column<double>(type: "float", nullable: false),
                    Density_Tmin_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Density_Tmax_Value = table.Column<double>(type: "float", nullable: false),
                    Density_Tmax_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    SurfaceTension_C1 = table.Column<double>(type: "float", nullable: false),
                    SurfaceTension_C2 = table.Column<double>(type: "float", nullable: false),
                    SurfaceTension_C3 = table.Column<double>(type: "float", nullable: false),
                    SurfaceTension_C4 = table.Column<double>(type: "float", nullable: false),
                    SurfaceTension_C5 = table.Column<double>(type: "float", nullable: false),
                    SurfaceTension_C6 = table.Column<double>(type: "float", nullable: false),
                    SurfaceTension_C7 = table.Column<double>(type: "float", nullable: false),
                    SurfaceTension_Tmin_Value = table.Column<double>(type: "float", nullable: false),
                    SurfaceTension_Tmin_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    SurfaceTension_Tmax_Value = table.Column<double>(type: "float", nullable: false),
                    SurfaceTension_Tmax_Unit = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CreatedOn = table.Column<DateTime>(type: "datetime2", nullable: false),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    DeletedOnUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Order = table.Column<int>(type: "int", nullable: false, defaultValue: 0)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ChemicalComponents", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ChemicalComponents");
        }
    }
}
