// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Databases;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260817222411_AddLastFlowsheetByProjectWorkspaceState")]
    partial class AddLastFlowsheetByProjectWorkspaceState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Server.Entities.BaseStructure.Components.ChemicalComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AcentricFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("AcentricFactorPitzer")
                        .HasColumnType("double precision");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CriticalZ")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GasEnthalpyEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("IntegratedGasCpWithHvap");

                    b.Property<string>("GasHeatCapacityEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("AlyLee");

                    b.Property<string>("GasThermalConductivityEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("PolynomialRational");

                    b.Property<string>("GasViscosityEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("Dippr102");

                    b.Property<string>("HeatOfVaporizationEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("Dippr106");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LiquidDensityEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("Rackett");

                    b.Property<string>("LiquidEnthalpyEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("IntegratedLiquidCp");

                    b.Property<string>("LiquidHeatCapacityEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("Polynomial");

                    b.Property<string>("LiquidThermalConductivityEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("Polynomial4");

                    b.Property<string>("LiquidViscosityEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("Dippr101");

                    b.Property<double>("MolecularWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SaturatedMolarVolumeEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("Rackett");

                    b.Property<string>("SaturationTemperatureEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("FromVaporPressureSecant");

                    b.Property<string>("SecondaryFamily")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StructuralFormula")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SurfaceTensionEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("Dippr106");

                    b.Property<string>("VaporPressureEquationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("ExtendedAntoine");

                    b.HasKey("Id");

                    b.ToTable("ChemicalComponents");
                });

            modelBuilder.Entity("Server.Entities.Projects.ProjectChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NewValueJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<long>("ProjectVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "ProjectId", "OccurredOnUtc");

                    b.HasIndex("TenantId", "ProjectId", "ProjectVersion");

                    b.HasIndex("TenantId", "ProjectId", "UserId", "OperationId")
                        .HasFilter("\"OperationId\" IS NOT NULL");

                    b.ToTable("ProjectChangeLogs", (string)null);
                });

            modelBuilder.Entity("Server.Entities.Projects.ProjectCollaborator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastOpenedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId");

                    b.HasIndex("TenantId", "ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectCollaborators", (string)null);
                });

            modelBuilder.Entity("Server.Entities.Projects.ProjectDiagramRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanvasStateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiagramNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TenantId", "ProjectId", "DiagramNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "ProjectId", "Order");

                    b.ToTable("ProjectDiagrams", (string)null);
                });

            modelBuilder.Entity("Server.Entities.Projects.ProjectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveUnitSystemName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CameraConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentDesignConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NamingConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PlantElevationUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("PlantElevationValue")
                        .HasColumnType("double precision");

                    b.Property<string>("ReportConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ThermodynamicMethodId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitSystemsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TenantId", "Name");

                    b.HasIndex("TenantId", "OwnerUserId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Server.Entities.Projects.ProjectUserWorkspaceState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpandedDiagramTypeCodesJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDiagramExplorerCollapsed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProjectExplorerCollapsed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastFlowsheetId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastFlowsheetIdsByProjectJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("LastProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectUserWorkspaceStates", (string)null);
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.BinaryInteractionParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentI_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentJ_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ParameterType")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ComponentI_Id");

                    b.HasIndex("ComponentJ_Id");

                    b.HasIndex("MethodId");

                    b.ToTable("BinaryInteractionParameters");
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.MethodComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MatrixIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("MethodId", "ComponentId")
                        .IsUnique();

                    b.ToTable("MethodComponents");
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.ThermodynamicMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LiquidModel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("VaporModel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ThermodynamicMethods");
                });

            modelBuilder.Entity("Server.Entities.UserManagement.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Server.Entities.UserManagement.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Server.Entities.UserManagement.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.UserManagement.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Server.Entities.UserManagement.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entities.BaseStructure.Components.ChemicalComponent", b =>
                {
                    b.OwnsOne("Server.Entities.StoredAmount", "BoilingPoint", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("BoilingPoint_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("BoilingPoint_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "CombustionEnthalpy", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CombustionEnthalpy_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("CombustionEnthalpy_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "CriticalPressure", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CriticalPressure_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("CriticalPressure_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "CriticalTemperature", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CriticalTemperature_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("CriticalTemperature_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "CriticalVolume", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CriticalVolume_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("CriticalVolume_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "Density", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("C1")
                                .HasColumnType("double precision")
                                .HasColumnName("Density_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("double precision")
                                .HasColumnName("Density_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("double precision")
                                .HasColumnName("Density_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("double precision")
                                .HasColumnName("Density_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("double precision")
                                .HasColumnName("Density_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("double precision")
                                .HasColumnName("Density_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("double precision")
                                .HasColumnName("Density_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Density_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Density_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Density_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Density_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "EnthalpyForm", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("EnthalpyForm_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("EnthalpyForm_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "EntropyForm", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("EntropyForm_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("EntropyForm_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "GasHeatCapacity", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("C1")
                                .HasColumnType("double precision")
                                .HasColumnName("GasHeatCapacity_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("double precision")
                                .HasColumnName("GasHeatCapacity_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("double precision")
                                .HasColumnName("GasHeatCapacity_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("double precision")
                                .HasColumnName("GasHeatCapacity_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("double precision")
                                .HasColumnName("GasHeatCapacity_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("double precision")
                                .HasColumnName("GasHeatCapacity_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("double precision")
                                .HasColumnName("GasHeatCapacity_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("GasHeatCapacity_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("GasHeatCapacity_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("GasHeatCapacity_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("GasHeatCapacity_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "GasThermalCond", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("C1")
                                .HasColumnType("double precision")
                                .HasColumnName("GasThermalCond_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("double precision")
                                .HasColumnName("GasThermalCond_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("double precision")
                                .HasColumnName("GasThermalCond_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("double precision")
                                .HasColumnName("GasThermalCond_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("double precision")
                                .HasColumnName("GasThermalCond_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("double precision")
                                .HasColumnName("GasThermalCond_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("double precision")
                                .HasColumnName("GasThermalCond_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("GasThermalCond_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("GasThermalCond_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("GasThermalCond_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("GasThermalCond_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "GasViscosity", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("C1")
                                .HasColumnType("double precision")
                                .HasColumnName("GasViscosity_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("double precision")
                                .HasColumnName("GasViscosity_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("double precision")
                                .HasColumnName("GasViscosity_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("double precision")
                                .HasColumnName("GasViscosity_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("double precision")
                                .HasColumnName("GasViscosity_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("double precision")
                                .HasColumnName("GasViscosity_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("double precision")
                                .HasColumnName("GasViscosity_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("GasViscosity_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("GasViscosity_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("GasViscosity_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("GasViscosity_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "GibbsForm", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("GibbsForm_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("GibbsForm_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "HeatOfVaporization", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("C1")
                                .HasColumnType("double precision")
                                .HasColumnName("HeatOfVaporization_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("double precision")
                                .HasColumnName("HeatOfVaporization_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("double precision")
                                .HasColumnName("HeatOfVaporization_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("double precision")
                                .HasColumnName("HeatOfVaporization_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("double precision")
                                .HasColumnName("HeatOfVaporization_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("double precision")
                                .HasColumnName("HeatOfVaporization_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("double precision")
                                .HasColumnName("HeatOfVaporization_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("HeatOfVaporization_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("HeatOfVaporization_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("HeatOfVaporization_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("HeatOfVaporization_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "LiquidHeatCapacity", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("C1")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidHeatCapacity_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidHeatCapacity_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidHeatCapacity_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidHeatCapacity_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidHeatCapacity_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidHeatCapacity_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidHeatCapacity_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("LiquidHeatCapacity_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("LiquidHeatCapacity_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("LiquidHeatCapacity_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("LiquidHeatCapacity_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "LiquidThermalCond", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("C1")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidThermalCond_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidThermalCond_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidThermalCond_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidThermalCond_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidThermalCond_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidThermalCond_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidThermalCond_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("LiquidThermalCond_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("LiquidThermalCond_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("LiquidThermalCond_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("LiquidThermalCond_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "LiquidViscosity", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("C1")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidViscosity_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidViscosity_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidViscosity_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidViscosity_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidViscosity_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidViscosity_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("double precision")
                                .HasColumnName("LiquidViscosity_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("LiquidViscosity_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("LiquidViscosity_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("LiquidViscosity_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("LiquidViscosity_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "MeltingPoint", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("MeltingPoint_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("MeltingPoint_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "SurfaceTension", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("C1")
                                .HasColumnType("double precision")
                                .HasColumnName("SurfaceTension_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("double precision")
                                .HasColumnName("SurfaceTension_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("double precision")
                                .HasColumnName("SurfaceTension_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("double precision")
                                .HasColumnName("SurfaceTension_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("double precision")
                                .HasColumnName("SurfaceTension_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("double precision")
                                .HasColumnName("SurfaceTension_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("double precision")
                                .HasColumnName("SurfaceTension_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("SurfaceTension_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("SurfaceTension_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("SurfaceTension_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("SurfaceTension_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "VaporPressure", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("C1")
                                .HasColumnType("double precision")
                                .HasColumnName("VaporPressure_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("double precision")
                                .HasColumnName("VaporPressure_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("double precision")
                                .HasColumnName("VaporPressure_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("double precision")
                                .HasColumnName("VaporPressure_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("double precision")
                                .HasColumnName("VaporPressure_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("double precision")
                                .HasColumnName("VaporPressure_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("double precision")
                                .HasColumnName("VaporPressure_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("VaporPressure_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("VaporPressure_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("VaporPressure_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("double precision")
                                        .HasColumnName("VaporPressure_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents");

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "VolumeAsterisk", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("VolumeAsterisk_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("VolumeAsterisk_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents");

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.Navigation("BoilingPoint")
                        .IsRequired();

                    b.Navigation("CombustionEnthalpy")
                        .IsRequired();

                    b.Navigation("CriticalPressure")
                        .IsRequired();

                    b.Navigation("CriticalTemperature")
                        .IsRequired();

                    b.Navigation("CriticalVolume")
                        .IsRequired();

                    b.Navigation("Density")
                        .IsRequired();

                    b.Navigation("EnthalpyForm")
                        .IsRequired();

                    b.Navigation("EntropyForm")
                        .IsRequired();

                    b.Navigation("GasHeatCapacity")
                        .IsRequired();

                    b.Navigation("GasThermalCond")
                        .IsRequired();

                    b.Navigation("GasViscosity")
                        .IsRequired();

                    b.Navigation("GibbsForm")
                        .IsRequired();

                    b.Navigation("HeatOfVaporization")
                        .IsRequired();

                    b.Navigation("LiquidHeatCapacity")
                        .IsRequired();

                    b.Navigation("LiquidThermalCond")
                        .IsRequired();

                    b.Navigation("LiquidViscosity")
                        .IsRequired();

                    b.Navigation("MeltingPoint")
                        .IsRequired();

                    b.Navigation("SurfaceTension")
                        .IsRequired();

                    b.Navigation("VaporPressure")
                        .IsRequired();

                    b.Navigation("VolumeAsterisk")
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entities.Projects.ProjectChangeLog", b =>
                {
                    b.HasOne("Server.Entities.Projects.ProjectRecord", "Project")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.UserManagement.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Entities.Projects.ProjectCollaborator", b =>
                {
                    b.HasOne("Server.Entities.Projects.ProjectRecord", "Project")
                        .WithMany("Collaborators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.UserManagement.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Entities.Projects.ProjectDiagramRecord", b =>
                {
                    b.HasOne("Server.Entities.Projects.ProjectRecord", "Project")
                        .WithMany("Diagrams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Server.Entities.Projects.ProjectRecord", b =>
                {
                    b.HasOne("Server.Entities.UserManagement.ApplicationUser", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.BinaryInteractionParameter", b =>
                {
                    b.HasOne("Server.Entities.BaseStructure.Components.ChemicalComponent", "ComponentI")
                        .WithMany()
                        .HasForeignKey("ComponentI_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Entities.BaseStructure.Components.ChemicalComponent", "ComponentJ")
                        .WithMany()
                        .HasForeignKey("ComponentJ_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Entities.Thermodynamics.Methods.ThermodynamicMethod", "Method")
                        .WithMany("BinaryParameters")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentI");

                    b.Navigation("ComponentJ");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.MethodComponent", b =>
                {
                    b.HasOne("Server.Entities.BaseStructure.Components.ChemicalComponent", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Entities.Thermodynamics.Methods.ThermodynamicMethod", "Method")
                        .WithMany("MethodComponents")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Server.Entities.Projects.ProjectRecord", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("Collaborators");

                    b.Navigation("Diagrams");
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.ThermodynamicMethod", b =>
                {
                    b.Navigation("BinaryParameters");

                    b.Navigation("MethodComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
