// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Databases;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Server.Entities.BaseStructure.Components.ChemicalComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AcentricFactor")
                        .HasColumnType("float");

                    b.Property<double>("AcentricFactorPitzer")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("CriticalZ")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double>("MolecularWeight")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SecondaryFamily")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StructuralFormula")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ChemicalComponents", (string)null);
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.BinaryInteractionParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComponentI_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComponentJ_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ParameterType")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ComponentI_Id");

                    b.HasIndex("ComponentJ_Id");

                    b.HasIndex("MethodId");

                    b.ToTable("BinaryInteractionParameters", (string)null);
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.MethodComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MatrixIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("MethodId", "ComponentId")
                        .IsUnique();

                    b.ToTable("MethodComponents", (string)null);
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.ThermodynamicMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LiquidModel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("VaporModel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ThermodynamicMethods", (string)null);
                });

            modelBuilder.Entity("Server.Entities.UserManagement.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Server.Entities.UserManagement.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Server.Entities.UserManagement.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.UserManagement.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Server.Entities.UserManagement.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entities.BaseStructure.Components.ChemicalComponent", b =>
                {
                    b.OwnsOne("Server.Entities.StoredAmount", "BoilingPoint", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("BoilingPoint_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("BoilingPoint_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "CombustionEnthalpy", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("CombustionEnthalpy_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("CombustionEnthalpy_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "CriticalPressure", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("CriticalPressure_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("CriticalPressure_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "CriticalTemperature", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("CriticalTemperature_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("CriticalTemperature_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "CriticalVolume", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("CriticalVolume_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("CriticalVolume_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "Density", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("C1")
                                .HasColumnType("float")
                                .HasColumnName("Density_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("float")
                                .HasColumnName("Density_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("float")
                                .HasColumnName("Density_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("float")
                                .HasColumnName("Density_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("float")
                                .HasColumnName("Density_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("float")
                                .HasColumnName("Density_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("float")
                                .HasColumnName("Density_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Density_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("Density_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Density_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("Density_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "EnthalpyForm", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("EnthalpyForm_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("EnthalpyForm_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "EntropyForm", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("EntropyForm_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("EntropyForm_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "GasHeatCapacity", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("C1")
                                .HasColumnType("float")
                                .HasColumnName("GasHeatCapacity_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("float")
                                .HasColumnName("GasHeatCapacity_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("float")
                                .HasColumnName("GasHeatCapacity_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("float")
                                .HasColumnName("GasHeatCapacity_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("float")
                                .HasColumnName("GasHeatCapacity_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("float")
                                .HasColumnName("GasHeatCapacity_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("float")
                                .HasColumnName("GasHeatCapacity_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("GasHeatCapacity_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("GasHeatCapacity_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("GasHeatCapacity_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("GasHeatCapacity_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "GasThermalCond", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("C1")
                                .HasColumnType("float")
                                .HasColumnName("GasThermalCond_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("float")
                                .HasColumnName("GasThermalCond_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("float")
                                .HasColumnName("GasThermalCond_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("float")
                                .HasColumnName("GasThermalCond_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("float")
                                .HasColumnName("GasThermalCond_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("float")
                                .HasColumnName("GasThermalCond_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("float")
                                .HasColumnName("GasThermalCond_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("GasThermalCond_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("GasThermalCond_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("GasThermalCond_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("GasThermalCond_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "GasViscosity", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("C1")
                                .HasColumnType("float")
                                .HasColumnName("GasViscosity_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("float")
                                .HasColumnName("GasViscosity_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("float")
                                .HasColumnName("GasViscosity_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("float")
                                .HasColumnName("GasViscosity_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("float")
                                .HasColumnName("GasViscosity_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("float")
                                .HasColumnName("GasViscosity_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("float")
                                .HasColumnName("GasViscosity_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("GasViscosity_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("GasViscosity_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("GasViscosity_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("GasViscosity_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "GibbsForm", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("GibbsForm_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("GibbsForm_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "HeatOfVaporization", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("C1")
                                .HasColumnType("float")
                                .HasColumnName("HeatOfVaporization_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("float")
                                .HasColumnName("HeatOfVaporization_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("float")
                                .HasColumnName("HeatOfVaporization_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("float")
                                .HasColumnName("HeatOfVaporization_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("float")
                                .HasColumnName("HeatOfVaporization_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("float")
                                .HasColumnName("HeatOfVaporization_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("float")
                                .HasColumnName("HeatOfVaporization_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("HeatOfVaporization_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("HeatOfVaporization_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("HeatOfVaporization_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("HeatOfVaporization_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "LiquidHeatCapacity", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("C1")
                                .HasColumnType("float")
                                .HasColumnName("LiquidHeatCapacity_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("float")
                                .HasColumnName("LiquidHeatCapacity_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("float")
                                .HasColumnName("LiquidHeatCapacity_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("float")
                                .HasColumnName("LiquidHeatCapacity_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("float")
                                .HasColumnName("LiquidHeatCapacity_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("float")
                                .HasColumnName("LiquidHeatCapacity_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("float")
                                .HasColumnName("LiquidHeatCapacity_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("LiquidHeatCapacity_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("LiquidHeatCapacity_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("LiquidHeatCapacity_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("LiquidHeatCapacity_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "LiquidThermalCond", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("C1")
                                .HasColumnType("float")
                                .HasColumnName("LiquidThermalCond_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("float")
                                .HasColumnName("LiquidThermalCond_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("float")
                                .HasColumnName("LiquidThermalCond_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("float")
                                .HasColumnName("LiquidThermalCond_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("float")
                                .HasColumnName("LiquidThermalCond_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("float")
                                .HasColumnName("LiquidThermalCond_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("float")
                                .HasColumnName("LiquidThermalCond_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("LiquidThermalCond_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("LiquidThermalCond_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("LiquidThermalCond_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("LiquidThermalCond_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "LiquidViscosity", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("C1")
                                .HasColumnType("float")
                                .HasColumnName("LiquidViscosity_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("float")
                                .HasColumnName("LiquidViscosity_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("float")
                                .HasColumnName("LiquidViscosity_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("float")
                                .HasColumnName("LiquidViscosity_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("float")
                                .HasColumnName("LiquidViscosity_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("float")
                                .HasColumnName("LiquidViscosity_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("float")
                                .HasColumnName("LiquidViscosity_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("LiquidViscosity_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("LiquidViscosity_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("LiquidViscosity_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("LiquidViscosity_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "MeltingPoint", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("MeltingPoint_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("MeltingPoint_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "SurfaceTension", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("C1")
                                .HasColumnType("float")
                                .HasColumnName("SurfaceTension_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("float")
                                .HasColumnName("SurfaceTension_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("float")
                                .HasColumnName("SurfaceTension_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("float")
                                .HasColumnName("SurfaceTension_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("float")
                                .HasColumnName("SurfaceTension_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("float")
                                .HasColumnName("SurfaceTension_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("float")
                                .HasColumnName("SurfaceTension_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("SurfaceTension_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("SurfaceTension_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("SurfaceTension_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("SurfaceTension_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.BaseStructure.Components.CorrelationCoefficients", "VaporPressure", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("C1")
                                .HasColumnType("float")
                                .HasColumnName("VaporPressure_C1");

                            b1.Property<double>("C2")
                                .HasColumnType("float")
                                .HasColumnName("VaporPressure_C2");

                            b1.Property<double>("C3")
                                .HasColumnType("float")
                                .HasColumnName("VaporPressure_C3");

                            b1.Property<double>("C4")
                                .HasColumnType("float")
                                .HasColumnName("VaporPressure_C4");

                            b1.Property<double>("C5")
                                .HasColumnType("float")
                                .HasColumnName("VaporPressure_C5");

                            b1.Property<double>("C6")
                                .HasColumnType("float")
                                .HasColumnName("VaporPressure_C6");

                            b1.Property<double>("C7")
                                .HasColumnType("float")
                                .HasColumnName("VaporPressure_C7");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmax", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("VaporPressure_Tmax_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("VaporPressure_Tmax_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.OwnsOne("Server.Entities.StoredAmount", "Tmin", b2 =>
                                {
                                    b2.Property<Guid>("CorrelationCoefficientsChemicalComponentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UnitName")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("VaporPressure_Tmin_Unit");

                                    b2.Property<double>("Value")
                                        .HasColumnType("float")
                                        .HasColumnName("VaporPressure_Tmin_Value");

                                    b2.HasKey("CorrelationCoefficientsChemicalComponentId");

                                    b2.ToTable("ChemicalComponents", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CorrelationCoefficientsChemicalComponentId");
                                });

                            b1.Navigation("Tmax")
                                .IsRequired();

                            b1.Navigation("Tmin")
                                .IsRequired();
                        });

                    b.OwnsOne("Server.Entities.StoredAmount", "VolumeAsterisk", b1 =>
                        {
                            b1.Property<Guid>("ChemicalComponentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UnitName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("VolumeAsterisk_Unit");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("VolumeAsterisk_Value");

                            b1.HasKey("ChemicalComponentId");

                            b1.ToTable("ChemicalComponents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChemicalComponentId");
                        });

                    b.Navigation("BoilingPoint")
                        .IsRequired();

                    b.Navigation("CombustionEnthalpy")
                        .IsRequired();

                    b.Navigation("CriticalPressure")
                        .IsRequired();

                    b.Navigation("CriticalTemperature")
                        .IsRequired();

                    b.Navigation("CriticalVolume")
                        .IsRequired();

                    b.Navigation("Density")
                        .IsRequired();

                    b.Navigation("EnthalpyForm")
                        .IsRequired();

                    b.Navigation("EntropyForm")
                        .IsRequired();

                    b.Navigation("GasHeatCapacity")
                        .IsRequired();

                    b.Navigation("GasThermalCond")
                        .IsRequired();

                    b.Navigation("GasViscosity")
                        .IsRequired();

                    b.Navigation("GibbsForm")
                        .IsRequired();

                    b.Navigation("HeatOfVaporization")
                        .IsRequired();

                    b.Navigation("LiquidHeatCapacity")
                        .IsRequired();

                    b.Navigation("LiquidThermalCond")
                        .IsRequired();

                    b.Navigation("LiquidViscosity")
                        .IsRequired();

                    b.Navigation("MeltingPoint")
                        .IsRequired();

                    b.Navigation("SurfaceTension")
                        .IsRequired();

                    b.Navigation("VaporPressure")
                        .IsRequired();

                    b.Navigation("VolumeAsterisk")
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.BinaryInteractionParameter", b =>
                {
                    b.HasOne("Server.Entities.BaseStructure.Components.ChemicalComponent", "ComponentI")
                        .WithMany()
                        .HasForeignKey("ComponentI_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Entities.BaseStructure.Components.ChemicalComponent", "ComponentJ")
                        .WithMany()
                        .HasForeignKey("ComponentJ_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Entities.Thermodynamics.Methods.ThermodynamicMethod", "Method")
                        .WithMany("BinaryParameters")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentI");

                    b.Navigation("ComponentJ");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.MethodComponent", b =>
                {
                    b.HasOne("Server.Entities.BaseStructure.Components.ChemicalComponent", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Entities.Thermodynamics.Methods.ThermodynamicMethod", "Method")
                        .WithMany("MethodComponents")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Server.Entities.Thermodynamics.Methods.ThermodynamicMethod", b =>
                {
                    b.Navigation("BinaryParameters");

                    b.Navigation("MethodComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
